[package]
name = "wzs-web"
version = "0.1.0"
edition = "2024"

[lib]
name = "wzs_web"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
dotenvy = "0.15.7"
mysql = "26.0.1"
uuid = { version = "1.18.1", features = ["serde", "v4", "v7"] }

[dev-dependencies]
temp-env = "0.3.6"
